### ISSUE TITLE
Namespaces conflict has occured when creating "User" entity with Cosmos DB

### ISSUE THREAD

**Issue by karamem0** [Avanade/Beef#176]
# Summary

The code generated with `Compiler Error CS0104` is failing to build due to a conflict between the `Microsoft.Azure.Cosmos.User` and the `Business.Entities.User` class.

# Steps to repro

1. Create Cosmos DB project.

    ```
    dotnet new beef --company Foo --appname Bar --datasource Cosmos
    ```

1. Update entity.beed.yml.

    ```
    entityScope: Autonomous
    eventSubjectRoot: Foo
    eventSubjectFormat: NameOnly
    eventActionFormat: PastTense
    eventCasing: Lower
    eventSourceRoot: Foo/Bar
    eventSourceKind: Relative
    appBasedAgentArgs: true
    webApiAutoLocation: true
    refDataText: true
    entities:
      - name: User
        get: true
        create: true
        update: true
        delete: true
        dataModel: true
        autoImplement: Cosmos
        cosmosContainerId: User
        cosmosModel: Model.User
        properties:
          - name: UserId
            type: Guid
            uniqueKey: true
          - name: UserName
            type: string
    ```

3. Run CodeGen.

    ```
    cd Foo.Bar.CodeGen
    dotnet run all
    ```

# Suggestion

It works when adding `RefDataNamespace` namespace synonym to `User` class.
